version: '3.8'

services:
  clima-node:
    build: ./clima-node
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./clima-node:/app
      - /app/node_modules
    depends_on:
      - climanode_backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - climanode-network

  climanode_backend:
    build: ./climanode_backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=api.py
    volumes:
      - ./climanode_backend:/app
    networks:
      - climanode-network

  mqtt_tester:
    build: ./mqtt_tester
    volumes:
      - ./mqtt_tester:/app
    networks:
      - climanode-network

networks:
  climanode-network:
    driver: bridge